export const images = {
    placeholder: require('./PortraitPlaceholder.png'),
    avatar: require('./avatar.png'),
    image_placeholder: require('./image-placeholder.png'),
    bell: require('./bell.png'),
    deposit_circle: require('./deposit-circle.png'),
    deposit: require('./deposit.png'),
    qr_circle: require('./qr-circle.png'),
    qr: require('./qr.png'),
    react: require('./react.jpg'),
    scan_circle: require('./scan-circle.png'),
    scan: require('./scan.png'),
    search: require('./search.png'),
    withdraw_circle: require('./withdraw-circle.png'),
    withdraw: require('./withdraw.png'),
    visa: require('./visa.png'),
    momo: require('./momo_logo.png'),
    master_card: require('./master-card.png'),
    wallet: require('./wallet.png'),
    bank: require('./bank.png'),
    filter: require('./filter.png'),
    social: require('./social.png'),
    figma: require('./figma.png'),
    slack: require('./slack.png'),
    photoshop: require('./photoshop.png'),
    idea: require('./idea.png'),
    hide: require('./hide.png'),
}
